---
## <font color=#FF8181>Unit 8 - Exercises: </font>
In the following exercises, we shall be using __YahooFinancials__ to conduct analysis on historical stock prices. 
Implement the below code in the functions you have to build as part of __Tasks 1 - 2__. Make sure to explore the code to ensure you understand what each operation/method does to the underlying data.

If you have not used YahooFinancials before, please go to __Command Prompt__ and install YahooFinancials using the following command: `pip install yahoofinancials`

In [3]:
# Include code in your function:
import pandas as pd
from yahoofinancials import YahooFinancials
import numpy as np

# Note - the second date argument in .get_historical_price_data is excluded
data = YahooFinancials('AAPL').get_historical_price_data('2021-07-01', '2022-01-01', 'daily')
df = data['AAPL']['prices']
df = pd.DataFrame(df)
df = df[['formatted_date', 'high', 'low', 'close']]
df['formatted_date'] = pd.to_datetime(df['formatted_date'], format = '%Y-%m-%d')
df['Month'] = df['formatted_date'].dt.to_period('M')
display(df)

    formatted_date        high         low       close    Month
0       2021-07-01  137.330002  135.759995  137.270004  2021-07
1       2021-07-02  140.000000  137.750000  139.960007  2021-07
2       2021-07-06  143.149994  140.070007  142.020004  2021-07
3       2021-07-07  144.889999  142.660004  144.570007  2021-07
4       2021-07-08  144.059998  140.669998  143.240005  2021-07
..             ...         ...         ...         ...      ...
123     2021-12-27  180.419998  177.070007  180.330002  2021-12
124     2021-12-28  181.330002  178.529999  179.289993  2021-12
125     2021-12-29  180.630005  178.139999  179.380005  2021-12
126     2021-12-30  180.570007  178.089996  178.199997  2021-12
127     2021-12-31  179.229996  177.259995  177.570007  2021-12

[128 rows x 5 columns]

---
### <font color=#14F278> Task 1:  </font>


<font color=#14F278> **The purpose of this exercise is to obtain information on Apple stock prices for H2 2021 and calculate their minimum, maximum and average on a monthly basis. The task deliverable is producing the dataframe below:** </font>


<center>
    <div>
        <img src="..\images\aggregation_007.png"/>
    </div>
</center>



__Steps: Create a python function `agg_financials()` which does the following:__
- Scrapes historical data on Apple prices from __YahooFinancials__
- Constructs a DataFrame, containing the daily price observations for H2 2021 - columns 'high', 'low' and 'close'
- For each Month, calculates the maximum of 'high' column, minimum of 'low' column and average of 'close' column
- Stores result in a new DataFrame
- Resets Index to new DataFrame (to ensure that the Month values are in a column)
- Returns the new DataFrame

In [ ]:
# Solution

def agg_financials():
    from yahoofinancials import YahooFinancials
    data = YahooFinancials('AAPL').get_historical_price_data('2021-07-01', '2022-01-01', 'daily')
    df = data['AAPL']['prices']
    df = pd.DataFrame(df)
    df = df[['formatted_date', 'high', 'low', 'close']]
    df['formatted_date'] = pd.to_datetime(df['formatted_date'], format = '%Y-%m-%d')
    df['Month'] = df['formatted_date'].dt.to_period('M')
    df_group = df.groupby('Month').agg({'high':np.max, 'low':np.min, 'close':np.mean})
    df_group.reset_index(inplace = True)
    return df_group

In [ ]:
# Call the function and display returned objects
agg_financials()

---
### <font color=#14F278> Task 2:</font>

<font color=#14F278> **Task 2 is a variation of Task 1. The purpose of this exercise is to obtain information on Apple stock prices for H2 2021 and calculate their minimum, maximum and average on a monthly basis, this time however across all price columns. In that sense, Task 2 aims to enlarge the scope of analysis from Task 1 and produce a comprehensive summary table.  The task deliverable is producing the dataframe below:** </font>


<center>
    <div>
        <img src="..\images\aggregation_008.png"/>
    </div>
</center>


__Steps: Create a python function `summary_financials()` which does the following:__
- Scrapes historical data on Apple prices from __YahooFinancials__
- Constructs a DataFrame, containing the daily price observations for H2 2021 - columns 'high', 'low' and 'close'
- For each Month, calculates min, max and mean of each of the 3 columns - 'high', 'low', 'close'
- Stores result in a new DataFrame - __Note - you will have to drop column 'formatted_date' before aggregating__
- Resets Index to new DataFrame (to ensure that the Month values are in a column)
- Returns the new DataFrame

In [4]:
# Solution

def summary_financials():
    from yahoofinancials import YahooFinancials
    data = YahooFinancials('AAPL').get_historical_price_data('2021-07-01', '2022-01-01', 'daily')
    df = data['AAPL']['prices']
    df = pd.DataFrame(df)
    df = df[['formatted_date', 'high', 'low', 'close']]
    df['formatted_date'] = pd.to_datetime(df['formatted_date'], format = '%Y-%m-%d')
    df['Month'] = df['formatted_date'].dt.to_period('M')
    df.drop(columns = 'formatted_date', inplace = True)
    df_group = df.groupby('Month').agg([np.min, np.max, np.mean])
    df_group.reset_index(inplace = True)
    return df_group

In [5]:
# Call the function and display returned objects
summary_financials()

C:\Users\MaxBeck\AppData\Local\Temp\ipykernel_27848\1737271393.py:12: FutureWarning: The provided callable <function min at 0x0000027CAEDD9260> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df_group = df.groupby('Month').agg([np.min, np.max, np.mean])
C:\Users\MaxBeck\AppData\Local\Temp\ipykernel_27848\1737271393.py:12: FutureWarning: The provided callable <function max at 0x0000027CAEDD9120> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_group = df.groupby('Month').agg([np.min, np.max, np.mean])
C:\Users\MaxBeck\AppData\Local\Temp\ipykernel_27848\1737271393.py:12: FutureWarning: The provided callable <function mean at 0x0000027CAEDD9B20> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df_group = df.groupby('Month').agg([np.min, np.max, np.mean])

     Month        high                                 low              \
                   min         max        mean         min         max
0  2021-07  137.330002  150.000000  146.252383  135.759995  147.699997
1  2021-08  146.699997  153.490005  149.225909  144.500000  151.289993
2  2021-09  144.380005  157.259995  149.995239  141.270004  154.389999
3  2021-10  141.399994  153.169998  146.418570  138.270004  149.720001
4  2021-11  149.429993  165.699997  155.509048  147.479996  161.000000
5  2021-12  164.199997  182.130005  175.632275  157.800003  178.529999

                    close
         mean         min         max        mean
0  143.538571  137.270004  149.149994  145.139524
1  146.865454  145.520004  153.119995  148.177727
2  147.220475  141.500000  156.690002  148.306190
3  143.954761  139.139999  152.570007  145.563809
4  152.586190  147.869995  165.300003  154.255716
5  171.252727  161.839996  180.330002  173.552727

__NB__: *Solutions to these exercises are distributed separately in the form of a stand-alone unit at a later point in time. This is to ensure that consultants have had the chance to attempt the exercises autonomously, leveraging the reading materials and concept check solutions.*